// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace XetSharp
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "xetcore_native";





        [DllImport(__DllName, EntryPoint = "xet_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int xet_add(int a, int b);

        [DllImport(__DllName, EntryPoint = "xet_sub", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int xet_sub(int a, int b);

        [DllImport(__DllName, EntryPoint = "xet_multi", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int xet_multi(int a, int b);

        [DllImport(__DllName, EntryPoint = "xet_div", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int xet_div(int a, int b);


    }



}
